name: Run Unit Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    setup:
        runs-on: ubuntu-latest
        outputs:
            workspace: ${{ steps.checkout.outputs.workspace }}
        steps:
            -   name: Checkout Code
                id: checkout
                uses: actions/checkout@v4
                with:
                    path: ${{ github.workspace }}

            -   name: Set Up JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'adopt'
                    java-version: '17'

    cache:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            -   name: Cache Maven Dependencies
                uses: actions/cache@v4
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                    restore-keys: |
                        ${{ runner.os }}-maven-

    build:
        runs-on: ubuntu-latest
        needs: cache
        steps:
            -   name: Checkout Code Again
                uses: actions/checkout@v4
                with:
                    path: ${{ github.workspace }}

            -   name: Install Maven Dependencies
                run: mvn install -D skipTests -D skipITs
                working-directory: ${{ github.workspace }}

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            -   name: Checkout Code Again
                uses: actions/checkout@v4
                with:
                    path: ${{ github.workspace }}

            -   name: Run Unit Tests
                run: mvn test
                working-directory: ${{ github.workspace }}
                continue-on-error: false

    upload:
        runs-on: ubuntu-latest
        needs: test
        if: always()
        steps:
            -   name: Upload Test Results
                uses: actions/upload-artifact@v3
                with:
                    name: test-results
                    path: target/surefire-reports
