name: Run Unit Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout the code
                uses: actions/checkout@v4

            -   name: Set Up JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'adopt-openjdk'
                    java-version: '17'

    cache:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            -   name: Cache Maven dependencies
                uses: actions/cache@v4
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                    restore-keys: |
                        ${{ runner.os }}-maven-

    build:
        runs-on: ubuntu-latest
        needs: cache
        steps:
            -   name: Install Maven dependencies
                run: mvn install -DskipTests -DskipITs

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            -   name: Run tests
                run: mvn test
                continue-on-error: false

    upload:
        runs-on: ubuntu-latest
        needs: test
        if: always()
        steps:
            -   name: Upload the test results
                uses: actions/upload-artifact@v3
                with:
                    name: test-results
                    path: target/surefire-reports
