name: Issue Template
description: Use this template for creating issues.
title: Migrate from a multi-module structure to a single-module Maven project
body:
    - type: input
      id: title
      attributes:
          label: Title
          description: Provide a brief and descriptive title for the issue.
          placeholder: Migrate from a multi-module structure to a single-module Maven project
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: Description
          description: Describe the issue or feature request in detail. Include any steps to reproduce the issue if applicable.
          placeholder: We currently have a multi-module Maven project structure, but we want to simplify the project organization by transitioning to a single-module Maven structure. This change will help streamline the development process and improve overall project management.
      validations:
          required: true
