name: Pull Request Template
description: Use this template for creating pull requests.
title: refactor(structure): change the structure and enhance some dependencies
body:
    - type: input
      id: title
      attributes:
          label: Title
          description: Use a clear and descriptive title for your PR.
          placeholder: refactor(structure): change the structure and enhance some dependencies
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: Description
          description: Provide a detailed explanation of what changes were made, why they were necessary, and any relevant context.
          placeholder: This pull request addresses several issues to improve the project structure and code quality. The changes include transitioning from a multi-module Maven project to a single-module Maven structure, refactoring sorting algorithms for better educational alignment, improving variable naming conventions, and optimizing dependency management.
      validations:
          required: true

    - type: textarea
      id: fixes
      attributes:
          label: Fixes
          description: Reference any related issues by including `Fixes: #<issue_number>`. List any issues that your PR resolves.
          placeholder: Fixes: #7, #4, #3, #2
      validations:
          required: false
